### ISSUE TITLE
Navabar content overflow: scroll

### ISSUE THREAD

**Issue by chakrihacker** [samrayner/bootstrap-side-navbar#8]
when there is more content in navbar or browser is resized a scrollbar appears. Remove navbar's scrollbar and use browser default scrollbar

**Comment by samrayner** [comment]
The navbar must scroll independently of the main window as it is `position: fixed` to the top of the viewport. If it was not fixed to the top then as you scroll down on a page with a lot of main content you would have to scroll back to the top in order to navigate to another page.

This is why the class I used is `.navbar-fixed-side`. I don't plan to do a static version, sorry.
